#!/usr/bin/env bash
# Script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

if scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~; then
	echo "File transferred successfully to $username@$server_ip:~/"
else
	echo "Error: File transferr failed."
fi

