#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## a server
## Nginx listening on port 80
## Nginx queries at its root with a GET request
### Returns a page that contains the string Hello World!

apt-get -y update
apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

service nginx restart
