#!/usr/bin/env bash
# bash script to make /redirect_me redirect to another site
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Hello World!" > /usr/share/nginx/html/index.html
new_config="location \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n"
sed -i "/server_name _;/a $new_config" /etc/nginx/sites-available/default
service nginx restart

