#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy
echo '  listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 432896-web-01 100.26.53.19 check
	server 432896-web-02 18.208.119.136:80 check' | sudo tee /etc/haproxy/haproxy.cfg
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
service haproxy start
