#!/usr/bin/env bash
#transfers a file from our client to a server:

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path_to_file=$1
	ip=$2
	username=$3
	ssh_key=$4
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$ip":~/
fi
