#!/usr/bin/env bash
#Using what you did for task #0, make your fix short and sweet.
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
