#!/usr/bin/env bash
#the story of passwd
while IFS=: read -r username pw uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pw, more info about the user here: $gecos"
done < /etc/passwd