#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
num=0
while [ $num -lt 10 ]; do
	num=$((num + 1))
	if [ $num -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
done
