#!/usr/bin/env bash
# Bash script that loops from 1 to 10
num=0
while [ $num -lt 10 ]; do
	num=$((num + 1))
	if [ $num -eq 4 ]; then
		echo "bad luck"
	elif [ $num -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
