#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 using case statement
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        "4") echo "and then bad luck from China";;
        "9") echo "and then bad luck from Japan";;
        "17") echo "and then bad luck from Italy";;
    esac
    ((i++))
done
