#!/usr/bin/env bash
#Displays numbers from 1 to 20 using case statement
#"bad luck from China" for the 4th iteration
#"bad luck from Japan" for the 9th iteration
#"bad luck from Italy" for the 17th loop iteration
i=1
while [ $i -le 20 ]
do
    echo "$i"
    case $i in
        "4") echo "and then bad luck from China";;
        "9") echo "and then bad luck from Japan";;
        "17") echo "and then bad luck from Italy";;
    esac
    ((i++))
done
